# Generated by Django 3.0.1 on 2019-12-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('aadhar_id', models.BigIntegerField(db_column='AADHAR_ID')),
                ('patient_id', models.IntegerField(db_column='PATIENT_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('age', models.IntegerField(db_column='AGE')),
                ('gender', models.CharField(db_column='GENDER', max_length=10)),
                ('contact', models.CharField(db_column='CONTACT', max_length=15)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'PATIENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prognosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(db_column='APPOINTMENT_DATE')),
                ('problem_description', models.CharField(db_column='PROBLEM_DESCRIPTION', max_length=200)),
                ('number_of_days_suffering', models.IntegerField(db_column='NUMBER_OF_DAYS_SUFFERING')),
                ('recommended_disease', models.CharField(blank=True, db_column='RECOMMENDED_DISEASE', max_length=200, null=True)),
                ('bmi', models.FloatField(blank=True, db_column='BMI', null=True)),
                ('ecg', models.CharField(blank=True, db_column='ECG', max_length=200, null=True)),
                ('eeg', models.CharField(blank=True, db_column='EEG', max_length=200, null=True)),
                ('eda', models.CharField(blank=True, db_column='EDA', max_length=200, null=True)),
                ('lung_sound', models.CharField(blank=True, db_column='LUNG_SOUND', max_length=200, null=True)),
            ],
            options={
                'db_table': 'PROGNOSIS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_column='TIMESTAMP')),
                ('diagnosis', models.CharField(blank=True, db_column='DIAGNOSIS', max_length=200, null=True)),
                ('prescribed_medicine', models.CharField(blank=True, db_column='PRESCRIBED_MEDICINE', max_length=200, null=True)),
                ('comments', models.CharField(blank=True, db_column='COMMENTS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'TREATMENT',
                'managed': False,
            },
        ),
    ]
